
# General set up
language: cpp
#cache: apt
sudo: required
dist: trusty

# Build matrix set up
compiler:
 - gcc
# - clang
os:
 - linux
# - osx
env:
 - QT_VERSION=5.4.2
 - QT_VERSION=5.5.1
 - QT_VERSION=5.6.1
matrix:
  exclude:
    # only use clang on OS X
    - os: osx
      compiler: gcc
    # only use the qt available from homebrew
    - os: osx
      env: QT_VERSION=5.4.2
    - os: osx
      env: QT_VERSION=5.5.1
    - os: osx
      env: QT_VERSION=5.6

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

# Install dependencies
install:
 - sudo apt-get -y install qt55[QTPACKAGE]
 - QT_WITHOUT_DOTS=qt$(echo $QT_VERSION | grep -oP "[^\.]*" | tr -d '\n' | tr '[:upper:]' '[:lower]')
 - QT_PKG_PREFIX=$(echo $QT_WITHOUT_DOTS | cut -c1-4)
 - sudo apt-get install ${QT_PKG_PREFIX}base ${QT_PKG_PREFIX}svg ${QT_PKG_PREFIX}tools ${QT_PKG_PREFIX}webkit
# - source travis/prepare.sh # installs qt and cmake. need to source because some env vars are set from there

# Actual work
before_script:
 - source /opt/qt55/bin/qt55-env.sh
 - mkdir build
 - cd build
 - /opt/qt55/bin/qmake ../ICF_Report.pro -r -spec linux-g++
script:
- make -j4 && make all ARGS="-V"
