
# General set up
language: cpp
cache: apt

# Build matrix set up
compiler:
 - gcc
# - clang
os:
 - linux
# - osx
env:
 - QT_VERSION=5.4.2
 - QT_VERSION=5.5.1
 - QT_VERSION=5.6.1
matrix:
  exclude:
    # only use clang on OS X
    - os: osx
      compiler: gcc
    # only use the qt available from homebrew
    - os: osx
      env: QT_VERSION=5.4.2
    - os: osx
      env: QT_VERSION=5.5.1
    - os: osx
      env: QT_VERSION=5.6

# Install dependencies
install:
 - source travis/prepare.sh # installs qt and cmake. need to source because some env vars are set from there

# Actual work
before_script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ..
script:
- make -j4 && make test ARGS="-V"
